CREATE TABLE IF NOT EXISTS film (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(128) not null,
  description varchar(255),
  release_date date,
  duration integer,
  mpa_rating bigint,
  last_update timestamp
);

CREATE TABLE IF NOT EXISTS genre (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(128) not null
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id bigint,
  genre_id bigint,
  last_update timestamp,
  foreign key (film_id) references film(id),
  foreign key (genre_id) references genre(id)
);

CREATE TABLE IF NOT EXISTS mpa_rating (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(128) not null,
  description varchar(255)
);
ALTER TABLE film ADD FOREIGN KEY (mpa_rating) REFERENCES mpa_rating(id);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(128),
  login varchar(64) not null,
  email varchar(64) not null,
  birthday date,
  last_update timestamp
);

CREATE TABLE IF NOT EXISTS film_like (
  film_id bigint,
  user_id bigint,
  last_update timestamp,
  foreign key (film_id) references film(id),
  foreign key (user_id) references users(id)
);

CREATE TABLE IF NOT EXISTS user_friendship (
  user_id bigint,
  friend_id bigint,
  confirmed bool,
  last_update timestamp,
  foreign key (user_id) references users(id),
  foreign key (friend_id) references users(id)
);


